config:
    target: 'http://{{ $processEnvironment.HOST }}:8081'
    phases:
        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

        - duration: 60
          arrivalRate: 10

scenarios:
    - flow:
          - get:
                url: '/hitme'
