config:
    target: 'http://{{ $processEnvironment.HOST }}:8081'
    phases:
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
        - duration: 60
          arrivalRate: 10
        - duration: 5
          arrivalRate: 0
scenarios:
    - flow:
          - get:
                url: '/hitme'
